use_frameworks!

platform :ios, '9.0'
inhibit_all_warnings!
install! 'cocoapods',
:disable_input_output_paths => true,
:generate_multiple_pod_projects => true

target 'jieba_Example' do
  pod 'jieba', :path => '../'

  target 'jieba_Tests' do
    inherit! :search_paths

    
  end
end


post_install do |installer|
  #installer.pods_project.targets.each do |target|
  installer.pod_target_subprojects.flat_map { |p| p.targets }.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
